@baseUrl = http://localhost:3000
@JwtToken = {{authLogin.response.body.accessToken}}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Luders",
  "email": "luders@email.com",
  "password": "123456"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "Leonardo",
  "email": "leonardo@email.com"
}

### Delete user
# @name deleteUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "123456"
}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "leonardo@email.com",
  "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}
