@baseUrl = http://localhost:3001
@JwtToken = {{authLogin.response.body.accessToken}}


################### LOGIN ###################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "leonardo@email.com",
  "password": "123456"
}

################### PLACE ###################

### Create place
# @name createUser
POST {{baseUrl}}/place/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "AAA Drinks e Discoteca - PF",
  "code": null,
  "businessName": "AAA",
  "cnpj": "YYY.YYY.YYY/0001-YY",
  "cpf": "YYY.YYY.YYY-YY",
  "phone": "48999887790",
  "email": "aaa@email.com",
  "address": {
    "street": "Rua 13",
    "neighborhood": "Quarta linha"
  },
  "postalBox": {
    "street": "Rua Quinze",
    "neighborhood": "Docas"
  },
  "workTime": {
  "shift": "madrugada",
  "initHour": 23,
  "endHour": 6,
  "isDefault": true
  }
}

### Update place
# @name updateUser
PATCH {{baseUrl}}/place/me/5c156016-f744-439e-8400-9e6dfaef0582
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "ownerId": "697dc575-09d7-408f-a325-eb40f4390e43"
}

### Remove place
# @name removePlace
DELETE {{baseUrl}}/place/me/5c156016-f744-439e-8400-9e6dfaef0582
Authorization: Bearer {{JwtToken}}

### Find place
# @name findOnePlace
GET {{baseUrl}}/place/5c156016-f744-439e-8400-9e6dfaef0582
Authorization: Bearer {{JwtToken}}

### find all places
# @name findAllPlaces
GET {{baseUrl}}/place
Authorization: Bearer {{JwtToken}}

### Add work time
# @name AddWorkTime
POST {{baseUrl}}/place/work-time?placeId=5c156016-f744-439e-8400-9e6dfaef0582
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "shift": "manhã",
  "initHour": 6,
  "endHour": 13,
  "isDefault": false
}

### Update shared work time
# @name updateWorkTime
PATCH {{baseUrl}}/place/me/5c156016-f744-439e-8400-9e6dfaef0582/work-time
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "id": "d21b13b5-48a6-48c7-8dac-0233a3909df1",
  "initHour": 18,
  "endHour": 4
}

### Remove shared work time
# @name removeSharedWorkTime
DELETE {{baseUrl}}/place/me/work-time/59358951-b3bf-419c-8a8a-976b25f372f2?placeId=c6ad6d5f-1387-4941-80d0-ac57abde5238
Authorization: Bearer {{JwtToken}}

### find place work times
# @name findPlaceWorkTimes
GET {{baseUrl}}/place/work-time
Authorization: Bearer {{JwtToken}}

################### WORK TIME ###################

### Create work time
# @name CreateWorkTime
POST {{baseUrl}}/work-time
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "shift": "madrugada",
  "initHour": 0,
  "endHour": 6
}

### Update work time
# @name updateWorkTime
PATCH {{baseUrl}}/work-time/cece908b-f0a4-4c42-8040-60f7947d9272
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "shift": "feriado"
}

### Find work time
# @name findWorkTime
GET {{baseUrl}}/work-time/d21b13b5-48a6-48c7-8dac-0233a3909df1
Authorization: Bearer {{JwtToken}}

### Find all work times
# @name findAllWorkTimes
GET {{baseUrl}}/work-time?shift=personalizado
Authorization: Bearer {{JwtToken}}

### Find all owned work times
# @name findAllOwnedWorkTimes
GET {{baseUrl}}/work-time/me
Authorization: Bearer {{JwtToken}}

### Remove work time
# @name removeWorkTime
DELETE {{baseUrl}}/work-time/cece908b-f0a4-4c42-8040-60f7947d9272
Authorization: Bearer {{JwtToken}}

################### USER ###################

### Create user
# @name createUser
POST {{baseUrl}}/user
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "Rogério",
  "phone": "48999558883",
  "email": "rogerio@email.com",
  "role": "operator",
  "password": "123456",
  "workTime": {
    "shift": "madrugada",
    "initHour": 23,
    "endHour": 7
  },
  "motorcycle": "Yamaha, 2017, 300, Preta",
  "daily": 15
}

# {
#   "name": "Gabriel",
#   "email": "gabriel@email.com",
#   "phone": "(48) 99988-4469",
#   "role": "motoboy",
#   "password": "123456",
#   "motorcycle": "Yamaha, 2017, 300, Vermelha",
#   "daily": 30
# }

### Update my user
# @name updateUser
PATCH {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{ 
  "workTime": {
    "initHour": 18,
    "endHour": 4
  }
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/77765315-68b7-43c2-83f4-c4140afb244e
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "workTime": {
    "initHour": 9,
    "endHour": 15
  }
}

### Delete user
# @name deleteUser
DELETE {{baseUrl}}/user/924b2100-1474-4311-8cbd-156376cb171f
Authorization: Bearer {{JwtToken}}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "currentPassword": "1234567",
  "newPassword": "123456"
}

### Read my user
# @name readMyUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/77765315-68b7-43c2-83f4-c4140afb244e
Authorization: Bearer {{JwtToken}}

### Read all users
# @name readAllUsers
GET {{baseUrl}}/user
Authorization: Bearer {{JwtToken}}

### Read all motoboys
# @name readAllMotoboys
GET {{baseUrl}}/user/motoboy
Authorization: Bearer {{JwtToken}}

################### CUSTOMER ###################

### Create customer
# @name createCustomer
POST {{baseUrl}}/customer
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "José",
  "phone": "(48) 98855-0061",
  "address": {
    "street": "Avenida Carambolas",
    "complement": "logo ali",
    "neighborhood": "25 de março",
    "postalCode": "88955-000",
    "city": "Gaivota",
    "stateCode": "SC",
    "location": "19.8987, -155.6659"
  }
}

### Update customer
# @name updateCustomer
PATCH {{baseUrl}}/customer/874cb730-aa1e-4bc5-b8f4-736c4ccdeb34
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "Rogério",
  "address" : {
    "id": "e1daf5f8-425b-4576-a3a9-640a5a5e860e",
    "isDefault": true
  }
}

### Delete customer
# @name deleteCustomer
DELETE {{baseUrl}}/customer/d1dac663-5fdf-4e1d-b6c2-2cdacfaa91ba
Authorization: Bearer {{JwtToken}}

### add address
# @name addAddress
POST {{baseUrl}}/customer/0e8421a6-183a-4f04-906b-6b06dade5637/address
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "street": "Avenida Y",
  "neighborhood": "Maloca",
  "isDefault": true
}

### remove address
# @name removeAddress
DELETE {{baseUrl}}/customer/address/aaa628e2-f2c1-4925-80fb-cfb65a8651b0
Authorization: Bearer {{JwtToken}}

### find one customer
# @name findOneCustomer
GET {{baseUrl}}/customer/find
Authorization: Bearer {{JwtToken}}

### find all customers
# @name findAllCustomers
GET {{baseUrl}}/customer
Authorization: Bearer {{JwtToken}}

### find all address by customer
# @name findAddressesByCustomer
GET {{baseUrl}}/customer/874cb730-aa1e-4bc5-b8f4-736c4ccdeb34/address
Authorization: Bearer {{JwtToken}}

################### DELIVERY ###################

### Create delivery
# @name createDelivery
POST {{baseUrl}}/delivery/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "motoboy": "4fcd0dfc-b670-4595-84d5-b268f7bf1941",
  "customer": "874cb730-aa1e-4bc5-b8f4-736c4ccdeb34",
  "totalPurchase": 99.99,
  "deliveryTax": 9.99,
  "tip": 1.99,
  "paymentMethod": "money"
}

### Update delivery
# @name updateDelivery
PATCH {{baseUrl}}/delivery/me/c9d1f23f-9850-40f1-a507-63810d15745c
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "isPaid": true,
  "tip": 1.5
}

### Delete tip
# @name deleteTip
DELETE {{baseUrl}}/tip/beda2c00-b20a-45e8-9513-6335ca173918
Authorization: Bearer {{JwtToken}}

### Delete delivery
# @name deleteDelivery
DELETE {{baseUrl}}/delivery/me/e60ff51b-7cf7-4d0e-b232-84c136e021ca
Authorization: Bearer {{JwtToken}}

### Find all owned deliveries
# @name findAllOwnedDeliveries
GET {{baseUrl}}/delivery/me
Authorization: Bearer {{JwtToken}}

### Find delivery
# @name findDelivery
GET {{baseUrl}}/delivery/3f34e129-4036-4a75-ab73-b5231fb8731e
Authorization: Bearer {{JwtToken}}

### Find all deliveries
# @name findAllDeliveries
GET {{baseUrl}}/delivery?name=Leonardo
Authorization: Bearer {{JwtToken}}

### Find all paid deliveries
# @name findAllPaidDeliveries
GET {{baseUrl}}/delivery?isPaid=false
Authorization: Bearer {{JwtToken}}

################### VOUCHER ###################

### Create voucher
# @name createVoucher
POST {{baseUrl}}/voucher/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "amount": 9.99
}

### Create voucher for user
# @name createVoucherForUser
POST {{baseUrl}}/voucher/me/user/e9df887c-c0ce-4426-9493-5e09c7d998d0
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "amount": 40
}

### Update voucher
# @name updateVoucher
PATCH {{baseUrl}}/voucher/me/e9df887c-c0ce-4426-9493-5e09c7d998d0
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "description": "gasolina"
}

### Update voucher for user
# @name updateVoucherForUser
PATCH {{baseUrl}}/voucher/me/user/e9df887c-c0ce-4426-9493-5e09c7d998d0
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "id": "563d87c1-99ca-4f9e-a531-eaf30a752848",
  "description": "gasolina"
}

### Delete one voucher
# @name deleteOneVoucher
DELETE {{baseUrl}}/voucher/me/c78832de-4eb8-4efa-acc9-1d39cdb2baa1
Authorization: Bearer {{JwtToken}}

### Read one voucher
# @name readOneVoucher
GET {{baseUrl}}/voucher/79cf0dd3-904f-42c8-9afc-5d3b49309b2e
Authorization: Bearer {{JwtToken}}

### Read all vouchers
# @name readAllVouchers
GET {{baseUrl}}/voucher?type=payout&id=7ed2374c-7548-4d78-a0cb-e767f19faa09
Authorization: Bearer {{JwtToken}}

### Read all owned vouchers
# @name readAllOwnedVouchers
GET {{baseUrl}}/voucher/me
Authorization: Bearer {{JwtToken}}

################### PAYOUT ###################

### Preview motoboy payout
# @name previewPayout
GET {{baseUrl}}/payout/preview?id=4fcd0dfc-b670-4595-84d5-b268f7bf1941
Authorization: Bearer {{JwtToken}}

### Create motoboy payout
# @name createPayout
POST {{baseUrl}}/payout
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "Anthos"
}

### Read payout
# @name readPayout
GET {{baseUrl}}/payout/9fbae80f-af63-4835-81c0-db52571a6fdf
Authorization: Bearer {{JwtToken}}

### Read owned payouts
# @name readOwnedPayouts
GET {{baseUrl}}/payout/me
Authorization: Bearer {{JwtToken}}

### Read all payouts
# @name readPayout
GET {{baseUrl}}/payout?name=Anthos
Authorization: Bearer {{JwtToken}}

### Update payout
# @name updatePayout
PATCH {{baseUrl}}/payout/9fbae80f-af63-4835-81c0-db52571a6fdf
Authorization: Bearer {{JwtToken}}

### Update Payout.isClosed
# @name updatePayoutIsClosed
PATCH {{baseUrl}}/payout/9fbae80f-af63-4835-81c0-db52571a6fdf/true
Authorization: Bearer {{JwtToken}}

### Remove payout
# @name removePayout
DELETE {{baseUrl}}/payout/c96c855e-6ddb-44e0-a49b-6f53b5593399
Authorization: Bearer {{JwtToken}}

################### SETTLEMENT ###################

### Preview settlement
# @name previewSettlement
GET {{baseUrl}}/settlement/preview?name=Neo
Authorization: Bearer {{JwtToken}}

### Create settlement
# @name createSettlement
POST {{baseUrl}}/settlement
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "from": "26-10-2025",
  "to": "26-10-2025",
  "initValue": 50,
  "name": "Orochi"
}

### Read settlement
# @name readSettlement
GET {{baseUrl}}/settlement/71963d55-3f02-4e58-b062-350287858c4f
Authorization: Bearer {{JwtToken}}

### Read owned settlements
# @name readOwnedSettlements
GET {{baseUrl}}/settlement/me
Authorization: Bearer {{JwtToken}}

### Read all settlements
# @name readAllSettlements
GET {{baseUrl}}/settlement
Authorization: Bearer {{JwtToken}}

### Update settlement
# @name createSettlement
PATCH {{baseUrl}}/settlement/71963d55-3f02-4e58-b062-350287858c4f
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{ 
  "description": null 
}

### Update settlement.isClosed
# @name updateSettlementIsClosed
PATCH {{baseUrl}}/settlement/7f099db0-4530-4ea6-9a18-d7d0c317b33f/true
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

### Delete settlement
# @name deleteSettlement
DELETE {{baseUrl}}/settlement/7f099db0-4530-4ea6-9a18-d7d0c317b33f
Authorization: Bearer {{JwtToken}}
