@baseUrl = http://localhost:3000
@JwtToken = {{authLogin.response.body.accessToken}}


################### LOGIN ###################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "neo@email.com",
  "password": "123456"
}

################### USER ###################

### Create user
# @name createUser
POST {{baseUrl}}/user
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "Igor",
  "email": "igor@email.com",
  "phone": "48976020114",
  "role": "operator",
  "password": "123456",
  "motorcycle": "Honda, 2024, 150, Preta",
  "daily": 30
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "name": "Renato",
  "email": "renato@email.com",
  "phone": "48976020113",
  "role": "admin",
  "motorcycle": "Yamaha, 250, 2017, Vermelha",
  "daily": 45,
  "tip": 2.5
}

### Delete user
# @name deleteUser
DELETE {{baseUrl}}/user/1234
Authorization: Bearer {{JwtToken}}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "1234567"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{JwtToken}}

### Read all motoboys
# @name readAllMotoboys
GET {{baseUrl}}/user/motoboy
Authorization: Bearer {{JwtToken}}

################### DELIVERY ###################

### Create delivery
# @name createDelivery
POST {{baseUrl}}/delivery/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "motoboy": "0d4dc644-8149-4cd0-bb28-36564c326ef6",
  "name": "Leonardo, Avenida Brasil, 222, Mutuca",
  "totalPurchase": 22.89,
  "deliveryTax": 8.0,
  "paymentMethod": "PIX"
}

### Update delivery
# @name updateDelivery
PATCH {{baseUrl}}/delivery/me/98b97391-dfba-4c2d-9dfd-520215048e22
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "paid": true
}

### Delete delivery
# @name deleteDelivery
DELETE {{baseUrl}}/delivery/me/6393a4f0-edaa-4a44-95de-3b37967278cc
Authorization: Bearer {{JwtToken}}

### Find one owned delivery
# @name findOneOwnedDelivery
GET {{baseUrl}}/delivery/me/3e85163b-3cc2-4307-96a0-97010a98a344
Authorization: Bearer {{JwtToken}}

### Find all owned deliveries
# @name findAllOwnedDeliveries
GET {{baseUrl}}/delivery/me
Authorization: Bearer {{JwtToken}}

### Find all deliveries
# @name findAllDeliveries
GET {{baseUrl}}/delivery
Authorization: Bearer {{JwtToken}}

### Find all paid deliveries
# @name findAllPaidDeliveries
GET {{baseUrl}}/delivery/false
Authorization: Bearer {{JwtToken}}

################### VOUCHER ###################

### Create voucher
# @name createVoucher
POST {{baseUrl}}/voucher/me
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "amount": 3.5,
  "description": "caipirão"
}

### Create voucher for user
# @name createVoucherForUser
POST {{baseUrl}}/voucher/me/user/6ef22e5d-870f-4d60-98e3-d816722e87d0
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "amount": 22.0,
  "description": "queijo"
}

### Update voucher
# @name updateVoucher
PATCH {{baseUrl}}/voucher/me/cd8fab39-983e-494e-856c-68e3a36a798b
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "amount": 5.5
}

### Update voucher for user
# @name updateVoucherForUser
PATCH {{baseUrl}}/voucher/me/user/00c4381d-51c4-436a-8706-b284e120e331
Authorization: Bearer {{JwtToken}}
Content-Type: application/json

{
  "id": "cd8fab39-983e-494e-856c-68e3a36a798b",
  "amount": 5.5
}

### Delete one voucher
# @name deleteOneVoucher
DELETE {{baseUrl}}/voucher/me/50375c80-6f5e-4e03-9855-5e0141bd83c2
Authorization: Bearer {{JwtToken}}

### Read one voucher
# @name readOneVoucher
GET {{baseUrl}}/voucher/87e39325-c784-440d-946a-c115d85d8ec7
Authorization: Bearer {{JwtToken}}

### Read all vouchers by user
# @name readAllVouchersByUser
GET {{baseUrl}}/voucher/user/6ef22e5d-870f-4d60-98e3-d816722e87d0
Authorization: Bearer {{JwtToken}}

### Read all owned vouchers
# @name readAllOwnedVouchers
GET {{baseUrl}}/voucher/me
Authorization: Bearer {{JwtToken}}
